// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SacramentMeetingPlanner.Models;
using System;

namespace SacramentMeetingPlanner.Migrations
{
    [DbContext(typeof(SacramentMeetingContext))]
    [Migration("20171119000659_EndPrayer")]
    partial class EndPrayer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacramentMeetingPlanner.Models.PlannedMeeting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Meeting");

                    b.Property<string>("Conductor");

                    b.Property<string>("OpeningSong");

                    b.Property<string>("StartPrayer");

                    b.Property<string>("SacramentSong");

                    b.Property<string>("Sacrament");

                    b.Property<string>("SpeakerOne");

                    b.Property<string>("SpeakerTwo");

                    b.Property<string>("OptionalSong");

                    b.Property<string>("SpeakerThree");

                    b.Property<string>("ClosingSong");

                    b.Property<string>("EndPrayer");

                    b.HasKey("ID");

                    b.ToTable("PlannedMeeting");
                });
#pragma warning restore 612, 618
        }
    }
}
